In [201]:
%matplotlib inline
from matplotlib import pyplot as plt
import numpy as np

In [202]:
INPUT_SIZE = 21
EPOCH = 100
L_RATE = 0.01

TRAIN_SIZE=300
TEST_SIZE=100


# Activation function
Implement the activation function.
Return 1 if the input is greater than or equal to 0 and 0 otherwise.

In [203]:
    def activation_fn(input_vector):
        return 1 if input_vector >= 0  else 0

# Prediction
Run an input through the perceptron and return an output. 
Add the bias into the input vector and compute the inner product and apply the activation function.
Calculate the input vector * weights vector (including the bias' weight), send to the prediction function and get the result of the activation function.

In [204]:
    def predict(input_vector, weights):
        output = weights.T.dot(input_vector)  #The input vector multiply with the weights vector (including the bias' weight)
        result = activation_fn(output)
        return result

# Training the data
Change the weights vector according to the results at the training data set, running for the number of epochs:

For each input vector in epoch, 
1. Define the error as the difference between the desired output and the predicted output (error = labels_tr[i] - output).
(when the desired and predicted outputs are the same (both are 0 or both are 1), the error is 0, and when they are different, (0 and 1 or 1 and 0), the error either 1 or -1.
2. Calculate the new value of the weights vector by adding it to the multiply of the input with the error and the learning rate (wights + learning rate * error * input_vector).


In [205]:
    def train_weights(training_set, labels_tr, weights):
        #Iterate for the number of epochs requested
        for epoch in range(EPOCH):
            for i in range(labels_tr.shape[0]):
                    input_vector = np.insert(training_set[i], 0, 1) #Insert value -1 of the bias neuron to the input vector
                    output = predict(input_vector, weights)
                    error = labels_tr[i] - output  #Error rate: label-output
                    weights = weights + L_RATE * error * input_vector
        return weights


## The Perceptron

Data preperation

In [206]:
#Training set and labels
training_set = np.random.randint(2, size=(TRAIN_SIZE, INPUT_SIZE))
labels_tr = np.sum(training_set, axis=1)
labels_tr[labels_tr<=10] = 0
labels_tr[labels_tr>10] = 1

#Test set and labels
test_set = np.random.randint(2, size=(TEST_SIZE, INPUT_SIZE))
labels_te = np.sum(test_set, axis=1)
labels_te[labels_te<=10] = 0
labels_te[labels_te>10] = 1

print("**************TRAINING SET**************")
print(training_set)
print("**************LABELS TRAINING SET**************")
print(labels_tr)
print("**************TEST SET**************")
print(test_set)
print("**************LABELS TEST SET**************")
print(labels_te)


**************TRAINING SET**************
[[0 0 0 ... 0 1 1]
 [0 0 0 ... 0 1 0]
 [1 0 1 ... 0 0 1]
 ...
 [0 0 1 ... 1 0 1]
 [0 1 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]]
**************LABELS TRAINING SET**************
[0 0 0 1 0 0 1 0 1 1 0 1 0 0 0 1 0 1 1 1 1 0 0 1 1 1 0 0 0 1 0 1 1 0 1 1 0
 1 0 1 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 0
 0 0 0 1 0 0 1 1 0 1 0 1 0 0 0 1 0 0 1 1 1 0 1 1 1 1 1 0 0 1 1 1 1 0 1 0 0
 1 0 0 1 1 0 1 1 0 1 0 0 1 0 1 1 0 1 1 1 0 1 0 1 1 0 0 1 0 0 1 1 0 1 1 1 1
 1 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 1 1 0 0 1 1 0 0 0 0 1 0 1 1 1 0 0 0 1 0
 1 0 0 0 1 0 0 1 1 0 0 0 1 0 1 0 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 1 0
 0 1 1 0 0 0 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 0 1 1 0 0 1 1 1 0 0 0 0 1 1
 0 1 0 1 0 0 0 0 0 1 1 1 1 0 0 1 0 0 0 1 1 0 0 1 1 0 0 1 0 0 1 1 1 1 1 1 0
 1 1 0 0]
**************TEST SET**************
[[1 1 0 ... 0 0 1]
 [1 0 1 ... 1 0 0]
 [1 0 0 ... 1 1 0]
 ...
 [0 0 0 ... 1 0 1]
 [1 1 1 ... 0 0 0]
 [0 1 0 ... 0 0 1]]
**************LABELS TES

Initialize training weights eith the training data set 

In [207]:
weights = np.zeros(INPUT_SIZE+1)   #Initialize the weights vector. Add 1 for bias neuron

weights = train_weights(training_set, labels_tr, weights)

print("**************WEIGHTS AFTER TRAINING**************")
for (i, item) in enumerate(weights, start=0):
    print(i, "    ", round(item,2))

**************WEIGHTS AFTER TRAINING**************
0      -0.83
1      0.1
2      0.07
3      0.06
4      0.07
5      0.1
6      0.08
7      0.06
8      0.08
9      0.08
10      0.08
11      0.09
12      0.07
13      0.07
14      0.09
15      0.09
16      0.09
17      0.06
18      0.08
19      0.07
20      0.1
21      0.08


Testing the perceptron network and Calcolate the current accuracy

In [208]:
correct = 0

for i in range(labels_te.shape[0]):
    input_vector = np.insert(test_set[i], 0, 1) #Insert value 1 of the bias neuron to the input vector
    output = predict(input_vector, weights)
    if (labels_te[i] - output == 0):    #Output equals to label
        correct += 1
    accuracy = correct / TEST_SIZE
    
print("**************ACCURACY**************")
print (accuracy)

**************ACCURACY**************
0.99
